version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./videos:/app/videos
    environment:
      - MONGODB_URL=your_mongo_db_link