version: '3.8'

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/videos
  
  mongo:
    image: mongo:latest
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
