version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
      
  mongo:
   image: mongo:latest
   ports:
    - "27017:27017"
